### ISSUE TITLE
Crashes at startup, NameError

### ISSUE THREAD

**Issue by nils-van-zuijlen** [Nao974/choreograph-git#4]
```
Traceback (most recent call last):
  File "choreograph-git/./choreograph/choreograph.py", line 18, in <module>
    from interface.interface import *
  File "choreograph-git/choreograph/interface/interface.py", line 2, in <module>
    from interface.frame_interactive import *
  File "choreograph-git/choreograph/interface/frame_interactive.py", line 8, in <module>
    class Frame_Interactive(Canvas):
NameError: name 'Canvas' is not defined
```

Tk 8.6.11.1
Python 3.9.6
Manjaro Linux, zsh

**Comment by nils-van-zuijlen** [comment]
C'est certainement lié à l'utilisation d'imports `*`

**Comment by Nao974** [comment]
Il manquait l'import de la lib tkinter dans frame_interactive.py
Correction effectuée sur la branche hotfix-0.9
